version: '3.8'


services:
  frontend:
    image: sharmakeshav54126293/metaversefrontend:latest
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - "4173:4173"
    build:
      context: .
      dockerfile: ./docker/dockerfile.frontend
      args:
        - VITE_JWT_SECRET=${VITE_JWT_SECRET}
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_WS_URL=${VITE_WS_URL}
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
        - VITE_GOOGLE_CLIENT_SECRET=${VITE_GOOGLE_CLIENT_SECRET}
        - DATABASE_URL=${DATABASE_URL}
        - FRONTEND_URL=${FRONTEND_URL}

  backend:
    image: sharmakeshav54126293/metaversehttp:latest
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: ./docker/dockerfile.http
      args:
        - VITE_JWT_SECRET=${VITE_JWT_SECRET}
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_WS_URL=${VITE_WS_URL}
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
        - VITE_GOOGLE_CLIENT_SECRET=${VITE_GOOGLE_CLIENT_SECRET}
        - DATABASE_URL=${DATABASE_URL}
        - FRONTEND_URL=${FRONTEND_URL}


  websocket:
    image: sharmakeshav54126293/metaversews:latest
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - "8081:8081"
    build:
      context: .
      dockerfile: ./docker/dockerfile.ws
      args:
        - VITE_JWT_SECRET=${VITE_JWT_SECRET}
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_WS_URL=${VITE_WS_URL}
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
        - VITE_GOOGLE_CLIENT_SECRET=${VITE_GOOGLE_CLIENT_SECRET}
        - DATABASE_URL=${DATABASE_URL}
        - FRONTEND_URL=${FRONTEND_URL}

networks:
  default:
    driver: bridge
